[tool.ruff]
# By default Ruff enable all checks, so do nothing here
# select = [...]

# Specify files/directories to exclude (e.g., virtualenv or generated files)
exclude = [".venv", "__pycache__", "static", "templates"]

# Specify the maximum line length for the code
line-length = 120

# Add any ignored rules (e.g., if you want to skip specific linter checks)
lint.ignore = [
	"E501",		# line-too-long
]


[tool.ruff.format]
indent-style = "tab"
